List<String> prefixes = [
  "Romania (+40)",
  "United States (+1)",
  "United Kingdom (+44)",
  "France (+33)",
  "Germany (+49)",
  "Italy (+39)",
  "Spain (+34)",
  "Portugal (+351)",
  "Sweden (+46)",
  "Norway (+47)",
  "Denmark (+45)",
  "Finland (+358)",
  "Poland (+48)",
  "Czech Republic (+420)",
  "Slovakia (+421)",
  "Hungary (+36)",
  "Austria (+43)",
  "Switzerland (+41)",
];
